from __future__ import annotations

from translator.models import ParsedIntent


class CppRenderer:
    name = "cpp"

    def render(self, prompt: str, intent: ParsedIntent, mode: str = "gameplay", plan=None) -> str:
        return f'''// Beginner-friendly C++ starter generated by Nevora.
// Prompt: {prompt}
// Mode: {mode}
// Tip: Rename `GeneratedFeature` to match your gameplay/system feature name.

#include <iostream>
#include <string>

class GeneratedFeature {{
public:
  // Call this from your game loop or event bridge.
  void Run(const std::string& eventType) {{
    if (eventType != "input" && eventType != "tick" && eventType != "request") {{
      return; // Ignore unsupported events.
    }}

    std::cout << "Actions: {', '.join(intent.actions)}" << std::endl;
  }}
}};

int main() {{
  GeneratedFeature feature;
  feature.Run("input");
  return 0;
}}
'''
