from __future__ import annotations

from translator.models import ParsedIntent


class CSharpRenderer:
    name = "csharp"

    def render(self, prompt: str, intent: ParsedIntent, mode: str = "gameplay", plan=None) -> str:
        return f'''// Beginner-friendly C# starter generated by Nevora.
// Prompt: {prompt}
// Mode: {mode}
using System;

public class GeneratedFeature
{{
  // Call Run(...) from your Unity/engine event hook.
  public void Run(string eventType)
  {{
    if (eventType != "input" && eventType != "tick" && eventType != "request")
    {{
      return; // Ignore unsupported event types.
    }}

    Console.WriteLine("Actions: {', '.join(intent.actions)}");
  }}

  public static void Main()
  {{
    var feature = new GeneratedFeature();
    feature.Run("input");
  }}
}}
'''
