from __future__ import annotations

from translator.models import ParsedIntent


class GDScriptRenderer:
    name = "gdscript"

    def render(self, prompt: str, intent: ParsedIntent, mode: str = "gameplay", plan=None) -> str:
        return f'''# Beginner-friendly GDScript starter generated by Nevora.
# Prompt: {prompt}
# Mode: {mode}
extends Node

# Called when this node enters the scene tree.
func _ready() -> void:
    var event_type := "input"

    # Guard clause so only expected event categories are processed.
    if event_type not in ["input", "tick", "request"]:
        return

    print("Actions: {', '.join(intent.actions)}")
'''
