from __future__ import annotations

from translator.models import ParsedIntent


class JavaScriptRenderer:
    name = "javascript"

    def render(self, prompt: str, intent: ParsedIntent, mode: str = "gameplay", plan=None) -> str:
        return f'''// Beginner-friendly JavaScript starter generated by Nevora.
// Prompt: {prompt}
// Mode: {mode}

class GeneratedFeature {{
  // Call run(...) from your app/game event router.
  run(event) {{
    const eventType = event?.type;
    if (!["input", "tick", "request"].includes(eventType)) {{
      return; // Skip unsupported event categories.
    }}

    console.log("Actions: {', '.join(intent.actions)}");
  }}
}}

const feature = new GeneratedFeature();
feature.run({{ type: "input" }});
'''
